@echo off
setlocal enabledelayedexpansion
REM Change to the script directory (rust-blockchain)
cd /d "%~dp0"
echo ==== Running MSVC build helper ====
echo Calling vcvars64.bat...
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" || exit /b %ERRORLEVEL%
echo Setting LIBCLANG_PATH to LLVM bin folder...
set "LIBCLANG_PATH=C:\Program Files\LLVM\bin"
echo Ensuring MSVC Rust toolchain is installed...
rustup toolchain install stable-x86_64-pc-windows-msvc --no-self-update || exit /b %ERRORLEVEL%
echo Running cargo clean (MSVC toolchain)...
rustup run stable-x86_64-pc-windows-msvc cargo clean || exit /b %ERRORLEVEL%
echo Building with MSVC toolchain (this may take several minutes)...
rustup run stable-x86_64-pc-windows-msvc cargo build --bins -vv
exit /b %ERRORLEVEL%
